### PR TITLE
Add precommit with ruff-format

### PR DESCRIPTION
**Pull request by boxydog**
A start on #8.

### CODE REVIEW

**Comment by boxydog** [comment]
Oops, have to add the pre-commit check to github tests.

**Comment by boxydog** [comment]
Tests pass: https://github.com/boxydog/ingredient-parser/actions/runs/7807626621

**Comment by strangetom** [comment]
Looks good @boxydog, very happy to see there's only one minor formatting change when using ruff format.

A couple of requests:

- Add pre-commit to requirements-dev.txt
- Could you check that the rev of each of the pre-commit hooks is the latest. There are a couple of deprecation warnings in the results from the actions you linked to, and I think using the latest revs might fix that.
- Do you think it's worth adding the `--fix`` argument to the ruff hook?

I think it would also be good to add 
```
[tool.ruff.format]
docstring-code-format = true
```
to `pyproject.toml` since a number of functions have code examples in the docstrings.

**Comment by boxydog** [comment]
Made all requested changes.

**Pull request merged**
